version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP port for application communication
      - "15672:15672"   # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq-net

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq-producer
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq-net
    environment:
      RABBITMQ__HOST: rabbitmq  # You can use this value in your code instead of localhost
    tty: true  # For better console interaction

networks:
  rabbitmq-net:
    driver: bridge
